[package]
name = "dirent-console"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
